### ISSUE TITLE
Error on startup / missing Serial # from list

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/rdlWC#1]
Sometimes if an rdLogger packet is received while the software is starting up, it throws the following exception (packet from R0 received while starting up in this example):
```
added serial number to list: R0
java.lang.NullPointerException
        at SelectionPanel.updateList(SelectionPanel.java:71)
        at RDLUniversalDownload.packetReceived(RDLUniversalDownload.java:159)
        at RDLUniversalReader.capturedPacket(RDLUniversalReader.java:67)
        at RDLUniversalReader.tryPacket(RDLUniversalReader.java:82)
        at RDLUniversalReader.addChar(RDLUniversalReader.java:110)
        at RDLUniversalReader.serialEvent(RDLUniversalReader.java:126)
        at javax.comm.SerialPortEventTask.run(SerialPortEventTask.java:209)
```
If this happens, the serial number never shows up in the serial number selection list.  You have to close the software and restart it to get the serial number to show up in the list.

**Comment by Cdetviler** [comment]
updated error:

![capture](https://cloud.githubusercontent.com/assets/12413097/10080633/4ef66ed8-62b6-11e5-9f37-1fa166beba0e.PNG)

**Comment by Cdetviler** [comment]
The issue was that the selection list was being referenced before it was even initialized. I added an if statement that checks to make sure the selection list has been created before doing anything with thepackets
